### ISSUE TITLE
Encoded WAV file slow playback

### ISSUE THREAD

**Issue by jgujgu** [higuma/wav-audio-encoder-js#1]
Hey higuma,

I really appreciate the work you've done on this and the related libraries. These abstractions really help. I was hoping you might have greater insight into a misunderstanding of mine on how to properly encode the file, namely the fact that the `.wav` files I produce appear to be in slow motion (the weird clipping is also probably a side effect). 

Here is an example output file of mine:
[onefive.wav.zip](https://github.com/higuma/wav-audio-encoder-js/files/405672/onefive.wav.zip)

For the buffer, I use `Float32Array` arrays derived from this Web Audio API function: `analyser.getFloatTimeDomainData(array_float_time_domain)`, [here](https://github.com/jgujgu/transcription/blob/master/app/assets/javascripts/voice.js#L68) in my particular code. And [here](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatTimeDomainData) in the Mozilla docs.

In my experimentation, I've noticed that varying the `bufferLength = analyser.fftSize` that initializes the `Float32Array` either slows down or speeds up the playback of the recording: lower powers of 2 play back proportionally faster. Since these are powers of 2 up to 2048, there are only so many I could reasonably try.

The only other setting that seemed to drastically change the recording is the `sampleRate`, but this of course is set by the system itself. [Here](https://github.com/jgujgu/transcription/blob/master/app/assets/javascripts/voice.js#L180) is where I actually start encoding the `.wav`.

I may be doing something heinously wrong, and I understand that my problem may be out of the purview of maintaining the library itself. However, perhaps you can see an obvious logical mistake I have made. What am I messing up?

-jgujgu

**Comment by higuma** [comment]
Hi,

(I haven't checked your code but...) obtaining audio data using AnalyserNode is probably wrong. Because the purpose of AnalyserNode is visualization, it does not support stream data acquisition.

In other words, if you call getFloatTimeDomainData once and again after fftSize frames, it does not ensure 2nd data is the next to 1st. It may be the same as previous (obviously your case) or some frames may drop out.

The only way to get stream (continuous) data is using ScriptProcessorNode (so far). It uses callback function to get stream data by corrent order and timings (This is the way I used in WebAudioRecorder).

> Current Web Audio API says ScriptProcessorNode is deprecated and recommends WorkerNode object (since last year). But WorkerNode has not yet been implemented in any browsers.

Present (practical) Web Audio API has AnalyserNode and ScriptProcessorNode. But purposes are completely different.
- AnalyserNode - for visualization (ONLY!)
  - you can call .getTime(or Frequency)DomainData at any timing you want
  - you cannot get continuous data
- ScriptProcessorNode - for audio process (ONLY!)
  - you must use callback function to get continuous data
  - you cannot use some kind of API's in callback function (e.g. DOM, Canvas, SVG, etc.)

I once had an idea to use AnalyserNode for FFT audio process (digital filter). Then I read API draft deeply and finally found it is impossible.

Furthermore, I had another idea to visualize audio signal with ScriptProcessorNode for strictly-correct level monitoring. But audio process frequently stopped when I called canvas API in callback.

I hope it will help you.

**Comment by jgujgu** [comment]
Hi higuma,

Your explanation has been quite enlightening, and I thank you deeply for it. It will very likely set me on the right track. This makes everything so clear. :D

-Jeffrey
